### ISSUE TITLE
2017.12.09 공부한 내용

### ISSUE THREAD

**Issue by geoseong** [designdevelop/rdb-study#5]
참고 url : http://pyrasis.com/book/TheArtOfAmazonWebServices/Chapter13/06

1. AWS RDS인스턴스 생성
2. AWS RDS인스턴스와 MySQL Workbench연동
3. MySQL Workbench : Table Inspector, Schema Inspector(미리보기, 단축메뉴에서 찾을 수 있음)

`Wiki` 탭에서 블로그형식으로 올릴 예정.

또 뭐가 있었나요??

**Comment by designdevelop** [comment]
AWS RDS 한글 설정
참고 url : http://designdevelop.tistory.com/68

요약
  1. parameter group 생성
  2. parameter group 설정 변경 (utf-8)
  3. RDS 설정에서 DB parameter group을 방금 생성한 group으로 변경
  4. RDS 리부트

**Comment by geoseong** [comment]
`AWS RDS 접속권한 설정하기` Wiki에 사진이랑 같이 첨부해서 포스팅했으니 그거 보고 확인해주세여~
